version: '3.7'

services:
 app:
  container_name: app
  hostname: app
  networks:
    - cassandra
  build:
    context: ./app
    dockerfile: server.Dockerfile
  develop:
    watch:
      - action: sync
        path: ./app
        target: /app
      - action: rebuild
        path: ./app/requirements.txt
  environment:
      - CASSANDRA_IP_ADDRESS=172.28.1.3
      - CASSANDRA_KEYSPACE=roy
  depends_on:
      cas1:
          condition: service_healthy
      cas2:
          condition: service_healthy
      cas3:
          condition: service_healthy
  ports:
    - "8888:8888"

 seeder:
  container_name: seeder
  networks:
    - cassandra
  build:
    context: ./app
    dockerfile: Dockerfile
  depends_on:
      cas1:
          condition: service_healthy
      cas2:
          condition: service_healthy
      cas3:
          condition: service_healthy

 cas1:
    container_name: cas1
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: "cas1, cas2"
    networks:
      - cassandra
    hostname: cas1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

 cas2:
    container_name: cas2
    image: cassandra:latest
    hostname: cas2
    environment:
      CASSANDRA_SEEDS: "cas2"
    networks:
      - cassandra
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

 cas3:
    container_name: cas3
    image: cassandra:latest
    hostname: cas3
    environment:
      CASSANDRA_SEEDS: "cas2"
    networks:
      - cassandra
    ports:
      - "9044:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

networks:
  cassandra: